name: Deploy
on:
  push:
    # We only run this GitHub action upon new commits to `main`
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          folder: dist
          # Remove previous build files
          clean: true
permissions:
  contents: write